Added test to ensure extension rules pin the right rules_rust version (#3052)
A test will now fail if the version is not updated in the extension
rules.
```
==================== Test output for //test/bzlmod:bzl_ext_version_test:

running 1 test
test module_bzl_has_correct_version ... FAILED

failures:

---- module_bzl_has_correct_version stdout ----
    name = "rules_rust",
thread 'module_bzl_has_correct_version' panicked at external/rules_rust~/test/bzl_version/bzl_ext_version_test.rs:76:5:
assertion `left == right` failed: Core rules_rust and the dependency for the current module are out of sync.
  left: "0.55.0"
 right: "0.54.1"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    module_bzl_has_correct_version

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```