Drop references to `wasm-wasi` (#3027)
This avoids the following error when upgrading to Rust 1.85.0
```
ERROR: An error occurred during the fetch of repository 'crate_index_cargo_bindeps':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_andrebrisco/5f9b22deab82162fb4591147bb665052/external/rules_rust/crate_universe/private/crates_repository.bzl", line 60, column 50, in _crates_repository_impl
		metadata_path = splice_workspace_manifest(
	File "/private/var/tmp/_bazel_andrebrisco/5f9b22deab82162fb4591147bb665052/external/rules_rust/crate_universe/private/splicing_utils.bzl", line 175, column 12, in splice_workspace_manifest
		execute(
	File "/private/var/tmp/_bazel_andrebrisco/5f9b22deab82162fb4591147bb665052/external/rules_rust/crate_universe/private/common_utils.bzl", line 55, column 13, in execute
		fail(_EXECUTE_ERROR_MESSAGE.format(
Error in fail: Command [/private/var/tmp/_bazel_andrebrisco/5f9b22deab82162fb4591147bb665052/external/cargo_bazel_bootstrap/release/cargo-bazel, "splice", "--output-dir", /private/var/tmp/_bazel_andrebrisco/5f9b22deab82162fb4591147bb665052/external/crate_index_cargo_bindeps/splicing-output, "--splicing-manifest", /private/var/tmp/_bazel_andrebrisco/5f9b22deab82162fb4591147bb665052/external/crate_index_cargo_bindeps/splicing_manifest.json, "--config", /private/var/tmp/_bazel_andrebrisco/5f9b22deab82162fb4591147bb665052/external/crate_index_cargo_bindeps/cargo-bazel.json, "--cargo", /private/var/tmp/_bazel_andrebrisco/5f9b22deab82162fb4591147bb665052/external/rust_darwin_aarch64__aarch64-apple-darwin__nightly_tools/bin/cargo, "--rustc", /private/var/tmp/_bazel_andrebrisco/5f9b22deab82162fb4591147bb665052/external/rust_darwin_aarch64__aarch64-apple-darwin__nightly_tools/bin/rustc, "--cargo-lockfile", /Users/andrebrisco/Code/rules_rust/examples/crate_universe/cargo_bindeps/Cargo.lock] failed with exit code 1.
STDOUT ------------------------------------------------------------------------

STDERR ------------------------------------------------------------------------

error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `/var/folders/hf/phjl9q7501gb5wt_qr4ltn3m0000gn/T/.tmpSQqSeg/cargo_tree_rustc_wrapper.sh /private/var/tmp/_bazel_andrebrisco/5f9b22deab82162fb4591147bb665052/external/rust_darwin_aarch64__aarch64-apple-darwin__nightly_tools/bin/rustc - --crate-name ___ --print=file-names --target wasm32-wasi --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=split-debuginfo --print=crate-name --print=cfg` (exit status: 1)
  --- stderr
  error: Error loading target specification: Could not find specification for target "wasm32-wasi". Run `rustc --print target-list` for a list of built-in targets


Error: Failed to generate features

Caused by:
    Failed to run cargo tree: exit status: 101

Stack backtrace:
   0: std::backtrace::Backtrace::create
   1: anyhow::kind::Adhoc::new
   2: cargo_bazel::metadata::cargo_tree_resolver::TreeResolver::generate
   3: cargo_bazel::cli::splice::splice
   4: cargo_bazel::main
   5: std::sys::backtrace::__rust_begin_short_backtrace
   6: std::rt::lang_start::{{closure}}
   7: std::rt::lang_start_internal
   8: _main
```