Fix BCR presubmit pipeline (#3082)
Hopefully this resolves the following:
https://buildkite.com/bazel/bcr-presubmit/builds/9302#0193b38a-65b5-4be1-91b6-138d4ab9cc90
```
ERROR: The test module directory does not exist in the source archive: /Users/buildkite/builds/bk-macos-arm64-0n05/bazel-org-repo-root/output/extensions/bindgen/extensions/bindgen
Traceback (most recent call last):
  File "/Users/buildkite/builds/bk-macos-arm64-0n05/bazel/bcr-presubmit/bcr_presubmit.py", line 537, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/buildkite/builds/bk-macos-arm64-0n05/bazel/bcr-presubmit/bcr_presubmit.py", line 528, in main
    repo_location, config_file = prepare_test_module_repo(args.module_name, args.module_version, args.overwrite_bazel_version)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/buildkite/builds/bk-macos-arm64-0n05/bazel/bcr-presubmit/bcr_presubmit.py", line 269, in prepare_test_module_repo
    error("The test module directory does not exist in the source archive: %s" % test_module_root)
  File "/Users/buildkite/builds/bk-macos-arm64-0n05/bazel/bcr-presubmit/bcr_presubmit.py", line 58, in error
    raise BcrPipelineException("BCR Presubmit failed!")
BcrPipelineException: BCR Presubmit failed!
🚨 Error: The command exited with status 1
^^^ +++
```

My assumption is that `module_path` is an extension of where the
presubmit yaml exists relative to the root one. So this should finally
enable CI to run in th eright place with the correct dependency.