Fix module path for bcr testing (#3069)
This should hopefully address
```
ERROR: The test module directory does not exist in the source archive: /Users/buildkite/builds/bk-macos-arm64-bcva/bazel-org-repo-root/output/extensions/bindgen
Traceback (most recent call last):
  File "/Users/buildkite/builds/bk-macos-arm64-bcva/bazel/bcr-presubmit/bcr_presubmit.py", line 537, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/buildkite/builds/bk-macos-arm64-bcva/bazel/bcr-presubmit/bcr_presubmit.py", line 528, in main
    repo_location, config_file = prepare_test_module_repo(args.module_name, args.module_version, args.overwrite_bazel_version)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/buildkite/builds/bk-macos-arm64-bcva/bazel/bcr-presubmit/bcr_presubmit.py", line 269, in prepare_test_module_repo
    error("The test module directory does not exist in the source archive: %s" % test_module_root)
  File "/Users/buildkite/builds/bk-macos-arm64-bcva/bazel/bcr-presubmit/bcr_presubmit.py", line 58, in error
    raise BcrPipelineException("BCR Presubmit failed!")
BcrPipelineException: BCR Presubmit failed!
🚨 Error: The command exited with status 1
```